mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r'^scheduler/', include('scheduler.urls', namespace="scheduler")),
    url(r'^admin/', include(admin.site.urls)),
)

# Add this to get widgets.AdminDateWidget() working for non is_staff, is_superuser
# This must be placed before (r'^admin/(.*)', admin.site.root), as that gobals up everything
(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),

scheduler/urls.py
from django.conf.urls import patterns, url

from scheduler import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<item_id>\d+)/$', views.detail, name='detail')
)

scheduler/models.py
from datetime import datetime
from django.db import models
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.forms import ModelForm
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.widgets import HiddenInput
from django.forms import MultiWidget
from django.forms.widgets import SplitDateTimeWidget

class User(models.Model):
	user_name = models.CharField(max_length=200)
	user_color = models.CharField(max_length=6,default='CCCCFF')
	def __str__(self):
		return self.user_name

class ItemType(models.Model):
	type_name = models.CharField(max_length=200)
	def __str__(self):
		return self.type_name	

class Item(models.Model):
	item_type = models.ForeignKey(ItemType)
	item_name = models.CharField(max_length=200)
	item_desc = models.CharField(max_length=1000)
	def __str__(self):
		return self.item_name
    
class Checkout(models.Model):
	user = models.ForeignKey(User)
	item = models.ForeignKey(Item)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	
	def __str__(self):
		return self.user.user_name+" checked out "+self.item.item_name+" from "+str(self.start_time)+" to "+str(self.end_time)

class DateForm(forms.Form):
	date = forms.DateTimeField(widget=SelectDateWidget,initial=datetime.now)
				
class CheckoutForm(ModelForm):
	class Meta:
		model = Checkout
		exclude = {'item'}
		widgets = {
			'start_time': SplitDateTimeWidget(),
			'end_time': SplitDateTimeWidget(),
		}
		
	def checkConflicts(self,i,u,s,e):
		checkouts = Checkout.objects.filter(item=i)
		conflict = ""
		
		for c in checkouts:
			if (s >= c.start_time and s < c.end_time) or (e > c.start_time and e <= c.end_time) or (c.start_time > s and c.start_time < e) or (c.end_time > s and c.end_time < e):
				if u == c.user:
					conflict = "You already have the "+c.item.item_name+" reserved from "+c.start_time.strftime('%Y-%m-%d %H:%M')+" to "+c.end_time.strftime('%Y-%m-%d %H:%M')
				else:
					conflict = "Time conflict: "+c.user.user_name+" has the "+c.item.item_name+" reserved from "+c.start_time.strftime('%Y-%m-%d %H:%M')+" to "+c.end_time.strftime('%Y-%m-%d %H:%M')
			else:
				#print str(s)+" to "+str(e)+" for item "+str(i.id)+" is not between "+str(c.start_time)+" and "+str(c.end_time)
				continue
		
		return conflict
		
	# Validation
	def clean(self):
		cleaned_data = super(CheckoutForm, self).clean()
		start_time = cleaned_data.get("start_time")
		end_time = cleaned_data.get("end_time")
		user = cleaned_data.get("user")
		item = self.item
		#print "cleaning checkout form. item: "+str(item)+", start time "+str(start_time)+", end time "+str(end_time)

		if start_time and end_time:
			if start_time > end_time:
				raise forms.ValidationError("Start time must be before end time.")
			
			conflicts = self.checkConflicts(item,user,start_time,end_time)	
			if conflicts != "":
				raise forms.ValidationError(conflicts)

scheduler/views.py
from datetime import datetime
import dateutil.parser
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from scheduler.models import ItemType, Item, User, Checkout, DateForm, CheckoutForm

def index(request):
    item_type_list = ItemType.objects.all().order_by('type_name')
    context = {'item_type_list': item_type_list}
    return render(request,'scheduler/index.html',context)
     
def detail(request, item_id):
    try:
        # Get constants for this detail view: which item this is, the user set.
        item = Item.objects.get(pk=item_id)
        users = User.objects.all().order_by('user_name')
        
        # Get the date (from the preset form, or default to today)
        # This is overly complex, fix (probably by not using SplitDateTime in the Checkouts model and not using two forms)
        date_form = DateForm()
        date = datetime.now()        
        if request.method == "POST": 
        	if request.POST.get("co_submit"): # Other form was submit
        		if request.POST.get("start_time_0") and request.POST.get("start_time_1"): #Hacky fallback: create datetime from the POST values of the split field
        			date = dateutil.parser.parse(request.POST.get("start_time_0")+" "+request.POST.get("start_time_1"))
        			date_form = DateForm(initial={'date':date})
        		else: # Fallback -- this should never happen
        			date_form = DateForm()
        			date = datetime.now()
        	else: # This form was submit
				date_form = DateForm(request.POST)
				if date_form.is_valid():
					date = date_form.cleaned_data['date']
				else: # Date form not valid fallback
					date = datetime.now()
        
        # Get the checkouts list -- filtered by date
        max_start = datetime(date.year,date.month,date.day,23,59) # Last minute of current day
        min_end = datetime(date.year,date.month,date.day,00,00) # First minute of current day
        checkouts = Checkout.objects.filter(item=item_id,start_time__lte=max_start,end_time__gte=min_end).order_by('start_time')
        all_checkouts = Checkout.objects.filter(item=item_id).order_by('start_time') # for testing
        
        # Checkout form
        c = Checkout(item=item,start_time=date,end_time=date) # Instantiate the item with pre-filled values
        
        if request.method == "POST" and not date_form.is_valid(): # Only validate/process this form if we don't have the data from the previous form
        	co_form = CheckoutForm(request.POST,instance=c)
        else:
        	co_form = CheckoutForm(instance=c)
        co_form.item = item
        
    	if request.method == "POST" and co_form.is_valid():
    		co_form.save()
		
    except Item.DoesNotExist:
        raise Http404
    return render(request, 'scheduler/detail.html', {
    	'item': item, 
    	'users': users, 
    	'date': date,
    	'checkouts': checkouts, 
    	'all_checkouts': all_checkouts,
    	'date_form': date_form,
    	'reserve_form': co_form
    })

scheduler/templates/scheduler/detail.html
{% load scheduler_extras %}

<style>
.checkout{
  width: 260px;
  position: absolute; /* Position checkout absolutely RELATIVE to day */
  margin-left:100px;
}
.day{
  border: 1px solid #DDDDDD;
  background-color: #EEEEEE;
  width: 360px;
  height: 360px;
  position: relative; /* Position checkout absolutely RELATIVE to day */
}
.day_guidelines{
  height: 360px;
  float: left;
  margin-right: 10px;
  padding-right: 10px;
  color: #CCCCCC;
}
.errorlist{
  color: #990000;
}
.guideline{
  position: absolute;
}
.testing {
 color: #999999;
}
</style>

<h1>{{ item }}</h1>

<p>{{ item.item_desc }}

<h2>Schedule for {{ date|date:"F d, Y" }}</h2>
<form action="{% url 'scheduler:detail' item.id %}" method="post">
	{% csrf_token %}
	{{ date_form }}
	<input type='submit' name='date_submit' value='Select Date'>
</form>

<div class='day'>
<div class='day_guidelines'>
   <div class='guideline' style='top:0px'>0:00 (midnight)</div>
   <div class='guideline' style='top:45px'>3:00 (3 AM)</div>
   <div class='guideline' style='top:90px'>6:00 (6 AM)</div>
   <div class='guideline' style='top:135px'>9:00 (9 AM)</div> 
   <div class='guideline' style='top:180px'>12:00 (noon)</div>
   <div class='guideline' style='top:225px'>15:00 (3 PM)</div>   
   <div class='guideline' style='top:270px'>18:00 (6 PM)</div>
   <div class='guideline' style='top:315px'>21:00 (9 PM)</div>
   <div class='guideline' style='top:360px'>0:00 (midnight)</div>
</div>

{% if checkouts %}
	{% for checkout in checkouts %}
		<div class='checkout' style='background-color:{{ checkout.user.user_color }};border: 1px solid {{ checkout.user.user_color|make_border_color }}; top:{{ checkout|calc_top:360 }}px;height:{{ checkout|calc_height:360 }}px'>
			{{ checkout.start_time|date:"H:i" }}-{{ checkout.end_time|date:"H:i" }} : {{ checkout.user.user_name }}
		</div>
	{% endfor %}
{% endif %}
</div>

<h2>Reserve</h2>
How to reserve:

<p>Pick a USER from list. (Ideally this would be login-system based.)

<p>DATE automatically fills in from the schedule date; you don't have to edit it. (Ideally, you wouldn't see the date, assuming checkouts can't cross multiple dates.)

<p>Fill in TIME in 24-hour time, e.g. 19:00 for 7:00 PM. (Ideally, this would be a nifty jQuery widget.)

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p>
<form action="{% url 'scheduler:detail' item.id %}" method="post">
	{% csrf_token %}
	{{ reserve_form }}
	<p><input type='submit' name='co_submit' value='Reserve'>
</form>

<div class='linkmenu'>
	<p><a href='/scheduler'>Menu</a>
</div>

<div class='testing'>
	<h3>All {{ item }} Checkouts (for Testing)</h3>
	{% if all_checkouts %}
		<ul>
		{% for checkout in all_checkouts %}
			<li>{{ checkout }}
		{% endfor %}
		</ul>
	{% else %}
		No checkouts for this item.
	{% endif %}
</div>

scheduler/templates/scheduler/index.html
{% if item_type_list %}
    <ul>
    {% for item_type in item_type_list %}
    	<li>{{ item_type.type_name }}</li>
    	<ul>
    	{% for item in item_type.item_set.all %}
        	<li><a href="/scheduler/{{ item.id }}/">{{ item.item_name }}</a></li>
        {% endfor %}
        </ul>
    {% endfor %}
    </ul>
{% else %}
    <p>No items are available.</p>
{% endif %}